#!/bin/bash

source configure

pushd ../build

../unpack/*/configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --libexecdir=/usr/lib \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    --enable-shared \
    --enable-threads-posix \
    --enable-__cxa_atexit \
    --enable-clocale-gnu \
    --enable-languages=c,c++ \
    --with-gmp=$AB_PACKAGE_GMP_INSTALL_DIR \
    --with-mpfr=$AB_PACKAGE_MPFR_INSTALL_DIR \
    | ABLog

popd
