#!/bin/bash

source configure

pushd ../unpack/*

./configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --libexecdir=/usr/sbin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    --disable-logger \
    --disable-syslogd \
    --disable-whois \
    --disable-servers \
    | tee ../../logs/040-configure.log

popd
