#!/bin/bash

source configure

pushd ../unpack/*

{
ABPatch

sed -i \
    -e 's/2010/002D/' \
    -e 's/2212/002D/' \
    -e 's/2018/0060/' \
    -e 's/2019/0027/' \
    font/devutf8/R.proto
    
} | tee ../../logs/020-patch.log

popd

