#!/bin/bash

source configure

pushd ../unpack/*

PAGE=A4 ./configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --enable-multibyte \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    | tee ../../logs/040-configure.log

popd
