#!/bin/bash

source configure

pushd ../unpack/*

mkdir -v build
pushd build

../configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    --with-root-prefix="" \
    --enable-elf-shlibs \
    --disable-evms \
    | tee ../../../logs/040-configure.log

popd
popd
