#!/bin/bash

source configure

pushd ../unpack/*

# make won't accept relative paths for DESTDIR, hence the sed fudge.
	make install \
		DESTDIR=$(pwd | sed 's:unpack.*::')pkg/debian \
		| tee ../../logs/060-make-install.log

popd
