#!/bin/bash

source configure

pushd ../unpack/*

make \
    etcdir=/etc/udev/extras \
    configdir=/etc/udev \
    EXTRAS="\
        extras/ata_id \
        extras/cdrom_id \
        extras/edd_id \
        extras/firmware \
        extras/floppy \
        extras/path_id \
        extras/rule_generator \
        extras/scsi_id \
        extras/usb_id \
        extras/volume_id" \
    | tee ../../logs/030-make-extras.log

popd
