#!/bin/bash

source configure

pushd ../pkg/debian

{
# remove info dir file
rm -v usr/share/info/dir

mkdir   -v bin
mv      -v usr/bin/find bin
sed -i -e 's@find:=${BINDIR}@find:=/bin@' usr/bin/updatedb 

} | tee ../../logs/060-fix-files.log

popd
