#!/bin/bash

source configure

pushd ../unpack/*

./configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --with-shared \
    --without-debug \
    --enable-widec \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    | tee ../../logs/040-configure.log

popd
