#!/bin/bash

source configure

pushd ../unpack

../unpack/*/configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --enable-shared \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    | tee ../logs/030-configure.log

popd
