#!/bin/bash

source configure

pushd ../unpack/*

./configure \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    --infodir=/usr/share/info \
    --mandir=/usr/share/man \
    | tee ../../logs/030-configure.log

popd
    
