#!/bin/bash

source configure

pushd ../unpack/*

./configure.gnu \
    --prefix=$AB_PACKAGE_CONFIGURE_PREFIX \
    -Dman1dir=/usr/share/man/man1 \
    -Dman3dir=/usr/share/man/man3 \
    -Dpager="/usr/bin/less -isR" \
    | tee ../../logs/040-configure.log

popd
