#!/bin/bash

source configure

pushd ../pkg/debian

# Remember to make any paths relative (i.e. ./usr rather than /usr)


install -dv ./lib/{firmware,udev/devices/{pts,shm}} \
	| tee ../../logs/035-fix-files.log
ABCheckImRoot && mknod -m0666 ./lib/udev/devices/null c 1 3 \
	| tee -a ../../logs/035-fix-files.log
ln -sv /proc/self/fd ./lib/udev/devices/fd \
	| tee -a ../../logs/035-fix-files.log
ln -sv /proc/self/fd/0 ./lib/udev/devices/stdin \
	| tee -a ../../logs/035-fix-files.log
ln -sv /proc/self/fd/1 ./lib/udev/devices/stdout \
	| tee -a ../../logs/035-fix-files.log
ln -sv /proc/self/fd/2 ./lib/udev/devices/stderr \
	| tee -a ../../logs/035-fix-files.log
ln -sv /proc/kcore ./lib/udev/devices/core \
	| tee -a ../../logs/035-fix-files.log

popd
