#!/bin/bash

source configure

pushd ../pkg/debian

{
ln -sv ../../lib/libbz2.so.1.0 usr/lib/libbz2.so
rm -v usr/bin/{bunzip2,bzcat,bzip2}
ln -v bin/bzip2 bin/bunzip2
ln -v bin/bzip2 bin/bzcat

rm -vrf usr/share/doc

} | tee -a ../../logs/060-fix-files.log

popd
